version: 2.1
jobs:
  test:
    docker:
      - image: python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install pytest
      - run:
          name: Run tests
          command: pytest tests/
