version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9

jobs:
  build-and-test:
    executor: python-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest tests/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test
